package mazin.sqlBuilder.behavior;

/*Generated by MPS */


public abstract class ExpressionWhereTerm_BehaviorDescriptor extends WhereTerm_BehaviorDescriptor {
  public ExpressionWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.ExpressionWhereTerm";
  }
}
