package mazin.sqlBuilder.behavior;

/*Generated by MPS */


public class ForEachWhereTerm_BehaviorDescriptor extends ExpressionWhereTerm_BehaviorDescriptor {
  public ForEachWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.ForEachWhereTerm";
  }
}
