package mazin.sqlBuilder.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FromBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FromBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.FromBlock";
  }
}
