package mazin.sqlBuilder.behavior;

/*Generated by MPS */


public class IfWhereTerm_BehaviorDescriptor extends ExpressionWhereTerm_BehaviorDescriptor {
  public IfWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.IfWhereTerm";
  }
}
