package mazin.sqlBuilder.behavior;

/*Generated by MPS */


public class NotNullWhereTerm_BehaviorDescriptor extends ExpressionWhereTerm_BehaviorDescriptor {
  public NotNullWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.NotNullWhereTerm";
  }
}
