package mazin.sqlBuilder.behavior;

/*Generated by MPS */


public class SelectQuery_BehaviorDescriptor extends SqlQuery_BehaviorDescriptor {
  public SelectQuery_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.SelectQuery";
  }
}
