package mazin.sqlBuilder.behavior;

/*Generated by MPS */


public class SimpleWhereTerm_BehaviorDescriptor extends WhereTerm_BehaviorDescriptor {
  public SimpleWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.SimpleWhereTerm";
  }
}
