package mazin.sqlBuilder.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.BaseMethodCall_BehaviorDescriptor;

public class SqlBuildersMethodCall_BehaviorDescriptor extends BaseMethodCall_BehaviorDescriptor {
  public SqlBuildersMethodCall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.SqlBuildersMethodCall";
  }
}
