package mazin.sqlBuilder.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class WhereBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public WhereBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "mazin.sqlBuilder.structure.WhereBlock";
  }
}
