package mazin.sqlBuilder.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_NotNullWhereTerm_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_NotNullWhereTerm_InferenceRule() {
  }

  public void applyRule(final SNode term, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(term, "expression", true);
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:61cf2b56-4b15-46be-8cff-6bd918750d90(mazin.sqlBuilder.typesystem)", "2591744203542973801", 0, null);
      typeCheckingContext.createLessThanInequality((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:61cf2b56-4b15-46be-8cff-6bd918750d90(mazin.sqlBuilder.typesystem)", "2591744203542973793", true), (SNode) SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(term, "column", true), "column", false), "type", true), false, true, _info_12389875345);
    }
  }

  public String getApplicableConceptFQName() {
    return "mazin.sqlBuilder.structure.NotNullWhereTerm";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
