package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ColumnReference extends BaseConcept {
  public static final String concept = "mazin.sqlBuilder.structure.ColumnReference";
  public static final String TABLE = "table";
  public static final String COLUMN = "column";

  public ColumnReference(SNode node) {
    super(node);
  }

  public TableReference getTable() {
    return (TableReference) this.getReferent(TableReference.class, ColumnReference.TABLE);
  }

  public void setTable(TableReference node) {
    super.setReferent(ColumnReference.TABLE, node);
  }

  public Column getColumn() {
    return (Column) this.getReferent(Column.class, ColumnReference.COLUMN);
  }

  public void setColumn(Column node) {
    super.setReferent(ColumnReference.COLUMN, node);
  }

  public static ColumnReference newInstance(SModel sm, boolean init) {
    return (ColumnReference) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.ColumnReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ColumnReference newInstance(SModel sm) {
    return ColumnReference.newInstance(sm, false);
  }
}
