package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ExpressionWhereTerm extends WhereTerm {
  public static final String concept = "mazin.sqlBuilder.structure.ExpressionWhereTerm";
  public static final String EXPRESSION = "expression";

  public ExpressionWhereTerm(SNode node) {
    super(node);
  }

  public Expression getExpression() {
    return (Expression) this.getChild(Expression.class, ExpressionWhereTerm.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(ExpressionWhereTerm.EXPRESSION, node);
  }

  public static ExpressionWhereTerm newInstance(SModel sm, boolean init) {
    return (ExpressionWhereTerm) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.ExpressionWhereTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ExpressionWhereTerm newInstance(SModel sm) {
    return ExpressionWhereTerm.newInstance(sm, false);
  }
}
