package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ForEachWhereTerm extends ExpressionWhereTerm {
  public static final String concept = "mazin.sqlBuilder.structure.ForEachWhereTerm";

  public ForEachWhereTerm(SNode node) {
    super(node);
  }

  public static ForEachWhereTerm newInstance(SModel sm, boolean init) {
    return (ForEachWhereTerm) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.ForEachWhereTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ForEachWhereTerm newInstance(SModel sm) {
    return ForEachWhereTerm.newInstance(sm, false);
  }
}
