package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NotNullWhereTerm extends ExpressionWhereTerm {
  public static final String concept = "mazin.sqlBuilder.structure.NotNullWhereTerm";

  public NotNullWhereTerm(SNode node) {
    super(node);
  }

  public static NotNullWhereTerm newInstance(SModel sm, boolean init) {
    return (NotNullWhereTerm) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.NotNullWhereTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NotNullWhereTerm newInstance(SModel sm) {
    return NotNullWhereTerm.newInstance(sm, false);
  }
}
