package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SimpleWhereTerm extends WhereTerm {
  public static final String concept = "mazin.sqlBuilder.structure.SimpleWhereTerm";
  public static final String VALUE = "value";

  public SimpleWhereTerm(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(SimpleWhereTerm.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(SimpleWhereTerm.VALUE, value);
  }

  public static SimpleWhereTerm newInstance(SModel sm, boolean init) {
    return (SimpleWhereTerm) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.SimpleWhereTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SimpleWhereTerm newInstance(SModel sm) {
    return SimpleWhereTerm.newInstance(sm, false);
  }
}
