package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class SqlBuilder_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("4e0fa1e8-e45e-46a1-b8b4-12a5bfa6456c(mazin.sqlBuilder)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
