package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.baseLanguage.structure.IValidIdentifier;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.ClassConcept;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SqlBuilder extends BaseConcept implements IValidIdentifier {
  public static final String concept = "mazin.sqlBuilder.structure.SqlBuilder";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String FILTER_CLASS = "filterClass";
  public static final String QUERY = "query";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public SqlBuilder(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(SqlBuilder.NAME);
  }

  public void setName(String value) {
    this.setProperty(SqlBuilder.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(SqlBuilder.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(SqlBuilder.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(SqlBuilder.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(SqlBuilder.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(SqlBuilder.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(SqlBuilder.VIRTUAL_PACKAGE, value);
  }

  public ClassConcept getFilterClass() {
    return (ClassConcept) this.getReferent(ClassConcept.class, SqlBuilder.FILTER_CLASS);
  }

  public void setFilterClass(ClassConcept node) {
    super.setReferent(SqlBuilder.FILTER_CLASS, node);
  }

  public SqlQuery getQuery() {
    return (SqlQuery) this.getChild(SqlQuery.class, SqlBuilder.QUERY);
  }

  public void setQuery(SqlQuery node) {
    super.setChild(SqlBuilder.QUERY, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(SqlBuilder.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, SqlBuilder.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, SqlBuilder.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(SqlBuilder.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, SqlBuilder.SMODEL_ATTRIBUTE, node);
  }

  public static SqlBuilder newInstance(SModel sm, boolean init) {
    return (SqlBuilder) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.SqlBuilder", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SqlBuilder newInstance(SModel sm) {
    return SqlBuilder.newInstance(sm, false);
  }
}
