package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.BaseMethodCall;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.InstanceMethodDeclaration;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SqlBuildersMethodCall extends BaseMethodCall {
  public static final String concept = "mazin.sqlBuilder.structure.SqlBuildersMethodCall";

  public SqlBuildersMethodCall(SNode node) {
    super(node);
  }

  public InstanceMethodDeclaration getInstanceMethodDeclaration() {
    return this.ensureAdapter(InstanceMethodDeclaration.class, "baseMethodDeclaration", this.getBaseMethodDeclaration());
  }

  public void setInstanceMethodDeclaration(InstanceMethodDeclaration node) {
    this.setBaseMethodDeclaration(node);
  }

  public static SqlBuildersMethodCall newInstance(SModel sm, boolean init) {
    return (SqlBuildersMethodCall) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.SqlBuildersMethodCall", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SqlBuildersMethodCall newInstance(SModel sm) {
    return SqlBuildersMethodCall.newInstance(sm, false);
  }
}
