package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SqlQuery extends BaseConcept {
  public static final String concept = "mazin.sqlBuilder.structure.SqlQuery";

  public SqlQuery(SNode node) {
    super(node);
  }

  public static SqlQuery newInstance(SModel sm, boolean init) {
    return (SqlQuery) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.SqlQuery", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SqlQuery newInstance(SModel sm) {
    return SqlQuery.newInstance(sm, false);
  }
}
