package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class WhereBlock extends BaseConcept {
  public static final String concept = "mazin.sqlBuilder.structure.WhereBlock";
  public static final String TERM = "term";

  public WhereBlock(SNode node) {
    super(node);
  }

  public int getTermsCount() {
    return this.getChildCount(WhereBlock.TERM);
  }

  public Iterator<WhereTerm> terms() {
    return this.children(WhereTerm.class, WhereBlock.TERM);
  }

  public List<WhereTerm> getTerms() {
    return this.getChildren(WhereTerm.class, WhereBlock.TERM);
  }

  public void addTerm(WhereTerm node) {
    this.addChild(WhereBlock.TERM, node);
  }

  public void insertTerm(WhereTerm prev, WhereTerm node) {
    this.insertChild(prev, WhereBlock.TERM, node);
  }

  public static WhereBlock newInstance(SModel sm, boolean init) {
    return (WhereBlock) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.WhereBlock", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static WhereBlock newInstance(SModel sm) {
    return WhereBlock.newInstance(sm, false);
  }
}
