package mazin.sqlBuilder.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class WhereTerm extends BaseConcept {
  public static final String concept = "mazin.sqlBuilder.structure.WhereTerm";
  public static final String COLUMN = "column";

  public WhereTerm(SNode node) {
    super(node);
  }

  public ColumnReference getColumn() {
    return (ColumnReference) this.getChild(ColumnReference.class, WhereTerm.COLUMN);
  }

  public void setColumn(ColumnReference node) {
    super.setChild(WhereTerm.COLUMN, node);
  }

  public static WhereTerm newInstance(SModel sm, boolean init) {
    return (WhereTerm) SModelUtil_new.instantiateConceptDeclaration("mazin.sqlBuilder.structure.WhereTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static WhereTerm newInstance(SModel sm) {
    return WhereTerm.newInstance(sm, false);
  }
}
