package mazin.sqlBuilder.sandbox.sandbox;

/*Generated by MPS */


public class MyDTO {
  private int myI;
  private String myS;
  private double myMyDouble;

  public MyDTO(int i, String s, double d) {
    myI = i;
    myS = s;
    this.setMyDouble(d);
  }

  public int getMyI() {
    return myI;
  }

  public String getMyS() {
    return myS;
  }

  public double getMyDouble() {
    return this.myMyDouble;
  }

  private void setMyDouble(double value) {
    this.myMyDouble = value;
  }
}
